version: "3.9"
services:
  validator-list-accounts:
    container_name: validator_list_accounts
    image: gcr.io/prysmaticlabs/prysm/validator:stable
    command: accounts list --wallet-dir="/data/wallets" --wallet-password-file="/data/passwords/password.txt" --accept-terms-of-use="true" --goerli
    volumes:
      - ./prysm_data:/data